### ISSUE TITLE
Installs, and icon shows, but I can't interact further with the extension

### ISSUE THREAD

**Issue by clauseggers** [hjr265/gnome-shell-extension-services#1]
The only thing I get in my logs is this `<audit-1130> pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=packagekit comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'`.

Any ideas?

PS: It would be awesome if you would make the shown services be selectable from a preferences menu.

**Comment by hjr265** [comment]
@clauseggers Thanks for reporting this. To be honest, this extension is pretty much unmaintained now. I use this only personally, and in lack of any proper documentation for Gnome Extensions development, I have discontinued all enhancements here. This particular extension doesn't use D-Bus and makes some blocking function calls. I am sure using D-Bus would have fixed the issue you are facing anyway.

At this moment, due to my current work load elsewhere, I cannot promise anything new for this extension. I am sorry.

**Comment by clauseggers** [comment]
No worries! I know the Gnome system is horribly documented, so I fully understand.
